# Generated by Django 6.1 on 2026-08-22 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalanganSholat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halangan_sholat', to='akademik.siswa')),
            ],
            options={
                'verbose_name': 'Halangan Sholat',
                'verbose_name_plural': 'Halangan Sholat',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='SesiSholat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sholat', models.CharField(choices=[('subuh', 'Subuh'), ('dzuhur', 'Dzuhur'), ('ashar', 'Ashar'), ('maghrib', 'Maghrib'), ('isya', 'Isya')], max_length=10)),
                ('aktif', models.BooleanField(default=False)),
                ('jendela_mulai', models.TimeField(blank=True, null=True)),
                ('jendela_selesai', models.TimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_sholat_list', to='accounts.school')),
            ],
            options={
                'verbose_name': 'Sesi Sholat',
                'verbose_name_plural': 'Sesi Sholat',
                'unique_together': {('school', 'nama_sholat')},
            },
        ),
        migrations.CreateModel(
            name='AbsensiHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_masuk', models.TimeField(blank=True, null=True)),
                ('metode_masuk', models.CharField(blank=True, choices=[('qr_lokasi', 'QR Code + Lokasi GPS'), ('barcode_kartu', 'Barcode Kartu Siswa')], max_length=20, null=True)),
                ('lokasi_valid_masuk', models.BooleanField(default=False)),
                ('jam_pulang', models.TimeField(blank=True, null=True)),
                ('metode_pulang', models.CharField(blank=True, choices=[('qr_lokasi', 'QR Code + Lokasi GPS'), ('barcode_kartu', 'Barcode Kartu Siswa')], max_length=20, null=True)),
                ('lokasi_valid_pulang', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('hadir', 'Hadir Tepat Waktu'), ('terlambat', 'Terlambat'), ('alpa', 'Tanpa Keterangan'), ('izin', 'Izin/Sakit')], default='alpa', max_length=15)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_harian', to='akademik.siswa')),
            ],
            options={
                'verbose_name': 'Absensi Harian',
                'verbose_name_plural': 'Absensi Harian',
                'ordering': ['-tanggal'],
                'unique_together': {('siswa', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='AbsensiSholat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu_absen', models.TimeField(blank=True, null=True)),
                ('hadir', models.BooleanField(default=False)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_sholat', to='akademik.siswa')),
                ('sesi_sholat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi.sesisholat')),
            ],
            options={
                'verbose_name': 'Absensi Sholat',
                'verbose_name_plural': 'Absensi Sholat',
                'ordering': ['-tanggal'],
                'unique_together': {('siswa', 'sesi_sholat', 'tanggal')},
            },
        ),
    ]
