# Generated by Django 6.1 on 2026-09-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0001_initial'),
        ('accounts', '0002_school_aktif_jumat_school_aktif_kamis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HariLibur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(max_length=200)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hari_libur_list', to='accounts.school')),
            ],
            options={
                'verbose_name': 'Hari Libur',
                'verbose_name_plural': 'Hari Libur',
                'ordering': ['-tanggal'],
                'unique_together': {('school', 'tanggal')},
            },
        ),
    ]
