# Generated by Django 6.1 on 2026-09-19 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0002_harilibur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absensiharian',
            name='catatan_koreksi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='absensiharian',
            name='dikoreksi_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi_dikoreksi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absensiharian',
            name='dikoreksi_pada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
