# Generated by Django 6.1 on 2026-09-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0003_absensiharian_catatan_koreksi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensiharian',
            name='foto_masuk',
            field=models.ImageField(blank=True, help_text='Selfie saat absen masuk, buat bukti visual kalau ada kecurigaan/perlu dicek manual guru piket.', null=True, upload_to='absensi_selfie/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='absensiharian',
            name='foto_pulang',
            field=models.ImageField(blank=True, null=True, upload_to='absensi_selfie/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='absensisholat',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='absensi_sholat_selfie/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='absensisholat',
            name='lokasi_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='absensiharian',
            name='metode_masuk',
            field=models.CharField(blank=True, choices=[('selfie_lokasi', 'Selfie + Lokasi GPS'), ('barcode_kartu', 'Barcode Kartu Siswa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='absensiharian',
            name='metode_pulang',
            field=models.CharField(blank=True, choices=[('selfie_lokasi', 'Selfie + Lokasi GPS'), ('barcode_kartu', 'Barcode Kartu Siswa')], max_length=20, null=True),
        ),
    ]
