# Generated by Django 6.1 on 2026-09-19 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0004_absensiharian_foto_masuk_absensiharian_foto_pulang_and_more'),
        ('akademik', '0002_siswa_kode_kartu_siswa_unique_kode_kartu_per_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_masuk', models.TimeField(blank=True, null=True)),
                ('metode_masuk', models.CharField(blank=True, choices=[('barcode_kartu', 'Kartu (Kiosk)')], max_length=20, null=True)),
                ('jam_pulang', models.TimeField(blank=True, null=True)),
                ('metode_pulang', models.CharField(blank=True, choices=[('barcode_kartu', 'Kartu (Kiosk)')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('hadir', 'Hadir Tepat Waktu'), ('terlambat', 'Terlambat'), ('alpa', 'Tanpa Keterangan'), ('izin', 'Izin/Sakit')], default='alpa', max_length=15)),
                ('dikoreksi_pada', models.DateTimeField(blank=True, null=True)),
                ('catatan_koreksi', models.CharField(blank=True, max_length=255)),
                ('dikoreksi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi_guru_dikoreksi', to=settings.AUTH_USER_MODEL)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_guru', to='akademik.guru')),
            ],
            options={
                'verbose_name': 'Absensi Guru',
                'verbose_name_plural': 'Absensi Guru',
                'ordering': ['-tanggal'],
                'unique_together': {('guru', 'tanggal')},
            },
        ),
    ]
