# Generated by Django 5.2.17 on 2026-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0005_absensiguru'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesisholat',
            name='aktif_jumat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sesisholat',
            name='aktif_kamis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sesisholat',
            name='aktif_minggu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesisholat',
            name='aktif_rabu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sesisholat',
            name='aktif_sabtu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesisholat',
            name='aktif_selasa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sesisholat',
            name='aktif_senin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='absensiguru',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='absensiharian',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='absensisholat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='halangansholat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='harilibur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sesisholat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sesisholat',
            name='nama_sholat',
            field=models.CharField(choices=[('subuh', 'Subuh'), ('dhuha', 'Dhuha'), ('dzuhur', 'Dzuhur'), ('ashar', 'Ashar'), ('maghrib', 'Maghrib'), ('isya', 'Isya')], max_length=10),
        ),
    ]
