# Generated by Django 5.2.17 on 2026-09-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0006_sesisholat_aktif_jumat_sesisholat_aktif_kamis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensiguru',
            name='foto_masuk',
            field=models.ImageField(blank=True, null=True, upload_to='absensi_guru_selfie/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='absensiguru',
            name='foto_pulang',
            field=models.ImageField(blank=True, null=True, upload_to='absensi_guru_selfie/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='absensiguru',
            name='lokasi_valid_masuk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='absensiguru',
            name='lokasi_valid_pulang',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='absensiguru',
            name='metode_masuk',
            field=models.CharField(blank=True, choices=[('selfie_lokasi', 'Selfie + Lokasi GPS'), ('barcode_kartu', 'Kartu (Kiosk)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='absensiguru',
            name='metode_pulang',
            field=models.CharField(blank=True, choices=[('selfie_lokasi', 'Selfie + Lokasi GPS'), ('barcode_kartu', 'Kartu (Kiosk)')], max_length=20, null=True),
        ),
    ]
