# Generated by Django 6.1 on 2026-08-22 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akademik', '0002_siswa_kode_kartu_siswa_unique_kode_kartu_per_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('absen_masuk', 'Absen Masuk'), ('sholat_hadir', 'Hadir Sholat Berjamaah'), ('sholat_alpa', 'Tidak Ikut Sholat Tanpa Keterangan'), ('izin_disetujui', 'Pengajuan Izin Disetujui'), ('izin_ditolak', 'Pengajuan Izin Ditolak'), ('belum_absen', 'Belum Absen Sampai Batas Waktu')], max_length=20)),
                ('judul', models.CharField(max_length=150)),
                ('deskripsi', models.CharField(blank=True, max_length=255)),
                ('sudah_dibaca', models.BooleanField(default=False)),
                ('terkirim_whatsapp', models.BooleanField(default=False, help_text='Menandakan sudah/belum terkirim via WhatsApp API (bukan cuma tercatat di sistem).')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('penerima', models.ForeignKey(help_text='User Orang Tua yang menerima notifikasi ini.', on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_list', to=settings.AUTH_USER_MODEL)),
                ('siswa', models.ForeignKey(help_text='Notifikasi ini soal anak yang mana.', on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi_terkait', to='akademik.siswa')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
