# Generated by Django 6.1 on 2026-08-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='aktif_jumat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='aktif_kamis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='aktif_minggu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='aktif_rabu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='aktif_sabtu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='aktif_selasa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='aktif_senin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='metode_verifikasi',
            field=models.CharField(choices=[('qr_lokasi', 'QR Code + Lokasi GPS'), ('lokasi', 'Lokasi GPS Saja'), ('qr', 'QR Code Saja')], default='qr_lokasi', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin Sekolah'), ('guru', 'Guru / Wali Kelas'), ('orang_tua', 'Orang Tua'), ('siswa', 'Siswa')], max_length=20),
        ),
    ]
