# Generated by Django 6.1 on 2026-09-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_aktif_jumat_school_aktif_kamis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='metode_verifikasi',
            field=models.CharField(choices=[('selfie_lokasi', 'Selfie + Lokasi GPS'), ('lokasi', 'Lokasi GPS Saja')], default='selfie_lokasi', max_length=15),
        ),
    ]
