# Generated by Django 5.2.17 on 2026-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_school_metode_verifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='latitude_masjid',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude_masjid',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='radius_masjid_meter',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin Sekolah'), ('guru', 'Guru / Wali Kelas'), ('orang_tua', 'Orang Tua'), ('siswa', 'Siswa'), ('kiosk', 'Kiosk (Device)')], max_length=20),
        ),
    ]
