# Generated by Django 5.2.17 on 2026-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_school_latitude_masjid_school_longitude_masjid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='radius_masjid_meter',
            field=models.PositiveSmallIntegerField(blank=True, default=100, null=True),
        ),
    ]
