# Generated by Django 6.1 on 2026-08-22 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guru_list', to='accounts.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_list', to='accounts.school')),
                ('wali_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_diampu', to='akademik.guru')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
                'unique_together': {('school', 'nama_kelas')},
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(blank=True, max_length=20, null=True)),
                ('nama', models.CharField(max_length=150)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('aktif', models.BooleanField(default=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siswa_list', to='akademik.kelas')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_list', to='accounts.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
            },
        ),
        migrations.CreateModel(
            name='OrangTua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('no_hp', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orangtua_list', to='accounts.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('anak', models.ManyToManyField(related_name='orang_tua_list', to='akademik.siswa')),
            ],
            options={
                'verbose_name': 'Orang Tua',
                'verbose_name_plural': 'Orang Tua',
            },
        ),
        migrations.AddConstraint(
            model_name='siswa',
            constraint=models.UniqueConstraint(condition=models.Q(('nis__isnull', False)), fields=('school', 'nis'), name='unique_nis_per_school'),
        ),
    ]
