# Generated by Django 6.1 on 2026-08-22 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_aktif_jumat_school_aktif_kamis_and_more'),
        ('akademik', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='kode_kartu',
            field=models.CharField(blank=True, help_text='Kode unik barcode yang tercetak di kartu siswa fisik (metode absen alternatif selain QR HP).', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='siswa',
            constraint=models.UniqueConstraint(condition=models.Q(('kode_kartu__isnull', False)), fields=('school', 'kode_kartu'), name='unique_kode_kartu_per_school'),
        ),
    ]
