# Generated by Django 6.1 on 2026-09-19 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_siswa_kode_kartu_siswa_unique_kode_kartu_per_school'),
        ('perizinan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanIzinGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('sakit', 'Sakit'), ('izin_keluarga', 'Izin Keperluan Keluarga'), ('lainnya', 'Izin Lainnya')], max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('bukti', models.FileField(blank=True, null=True, upload_to='bukti_izin_guru/%Y/%m/')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=15)),
                ('catatan_peninjau', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('ditinjau_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='izin_guru_ditinjau', to=settings.AUTH_USER_MODEL)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_izin', to='akademik.guru')),
            ],
            options={
                'verbose_name': 'Pengajuan Izin Guru',
                'verbose_name_plural': 'Pengajuan Izin Guru',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
