# Generated by Django 5.2.17 on 2026-09-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0004_pengajuanizinguru_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuanizin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pengajuanizinguru',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
